name: Package and Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets. AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy website to S3
      run: aws s3 sync static/ s3://jaygovindsahu.com/
    
    - name: Deploy lambda function to S3
      run: |
        cd aws-cloudformation/lambda-send-email-function; zip lambda-send-email-function.zip lambda_function.py; cd ../..
        aws s3 cp aws-cloudformation/lambda-send-email-function/lambda-send-email-function.zip s3://jays-apps/payload/lambda-send-email-function/
    
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: website-stack
        template: aws-cloudformation/stack.yml
        parameter-overrides: "apiGatewayName=sendEmailApi,apiGatewayStageName=prod"
        no-fail-on-empty-changeset: 1